name: ci

on:
    push:
        branches:
            - main
    pull_request:

concurrency:
    group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
    cancel-in-progress: true

jobs:
    ci:
        name: Continuous Integration
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Source
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: Install Dependencies
              run: bun i

            - name: Run Lint Check
              run: bun run lint

            - name: Build Check
              env:
                  NODE_ENV: 'production'
                  VERSION: ${{ github.ref_name }}
              run: bun run build
